-- SetFlow seed data (Segment 02): a small built-in exercise library
-- (owner_user_id null = global, readable by every user). User-specific
-- sample data (plans/sessions) is created per-account by the app, not here,
-- because it must reference a real auth user id.

insert into public.exercises
  (name, description, primary_muscle_group, secondary_muscle_groups, equipment, cues, common_mistakes)
values
  ('Barbell Bench Press',
   'Flat barbell press for chest strength.',
   'Chest', array['Triceps','Shoulders'], array['barbell','bench'],
   array['Feet planted','Bar path over mid-chest','Elbows ~45 degrees'],
   array['Bouncing the bar off the chest','Flaring elbows to 90 degrees']),
  ('Incline Dumbbell Press',
   'Upper-chest focused dumbbell press on an incline bench.',
   'Chest', array['Shoulders','Triceps'], array['dumbbells','incline bench'],
   array['Elbows 45 degrees','Press up and slightly back'],
   array['Setting the incline too steep','Clanking the dumbbells at the top']),
  ('Bent-Over Barbell Row',
   'Horizontal pull for back thickness.',
   'Back', array['Biceps','Rear Delts'], array['barbell'],
   array['Flat back','Pull to the lower ribs','Squeeze at the top'],
   array['Standing too upright','Using momentum']),
  ('Lat Pulldown',
   'Vertical pull targeting the lats.',
   'Back', array['Biceps'], array['cable machine'],
   array['Chest up','Pull elbows down and back'],
   array['Leaning too far back','Pulling behind the neck']),
  ('Overhead Press',
   'Standing barbell press for shoulders.',
   'Shoulders', array['Triceps','Upper Chest'], array['barbell'],
   array['Squeeze glutes','Bar path close to the face','Lock out overhead'],
   array['Arching the lower back','Pressing around the chin']),
  ('Barbell Back Squat',
   'The primary lower-body strength lift.',
   'Legs', array['Glutes','Core'], array['barbell','squat rack'],
   array['Brace before descending','Knees track over toes','Hit depth'],
   array['Heels lifting','Collapsing knees inward']),
  ('Romanian Deadlift',
   'Hip hinge targeting hamstrings and glutes.',
   'Legs', array['Glutes','Lower Back'], array['barbell'],
   array['Soft knees','Push hips back','Bar close to the legs'],
   array['Squatting instead of hinging','Rounding the back']),
  ('Dumbbell Bicep Curl',
   'Standing alternating or simultaneous curls.',
   'Arms', array['Forearms'], array['dumbbells'],
   array['Elbows pinned to the sides','Control the lowering'],
   array['Swinging the torso','Half reps']),
  ('Cable Tricep Pushdown',
   'Cable extension for the triceps.',
   'Arms', array[]::text[], array['cable machine'],
   array['Elbows fixed','Full lockout at the bottom'],
   array['Letting elbows drift forward']),
  ('Plank',
   'Isometric core hold.',
   'Core', array['Shoulders'], array[]::text[],
   array['Straight line head to heels','Squeeze glutes','Breathe'],
   array['Hips sagging','Holding the breath'])
on conflict do nothing;
