// AUTO-GENERATED by scripts/export-glasses-workouts.mjs — do not edit by hand.
// Keith's real workout plans, baked into the glasses build (offline-safe).
// Re-run the script after editing workouts on the web, then rebuild the glasses app.

import type { EngineWorkout } from "../../../packages/workout-engine/src/engine";

export const WORKOUTS: EngineWorkout[] = [
  {
    "plan": {
      "id": "91e7d7ae-d0ed-4144-aad8-8810d3e5fa0d",
      "ownerUserId": "ac5fb54d-08bb-4c08-be85-5fd0dc0e277a",
      "title": "Day 1 · Push",
      "description": "Chest, shoulders, triceps",
      "estimatedDurationMinutes": 55,
      "createdAt": "2026-07-06T00:00:00.000Z",
      "updatedAt": "2026-07-06T00:00:00.000Z"
    },
    "steps": [
      {
        "step": {
          "id": "a1692271-a664-46d6-b52b-89b784f7d012",
          "workoutPlanId": "91e7d7ae-d0ed-4144-aad8-8810d3e5fa0d",
          "exerciseId": "81b0d141-0d35-4f7f-8fbd-421f8466772c",
          "orderIndex": 0,
          "setCount": 4,
          "targetReps": 6,
          "targetWeight": 135,
          "restSeconds": 150,
          "cue": "Brace, bar to mid-chest"
        },
        "exercise": {
          "id": "81b0d141-0d35-4f7f-8fbd-421f8466772c",
          "name": "Barbell Bench Press",
          "primaryMuscleGroup": "Chest",
          "cues": [
            "Feet planted",
            "Bar path over mid-chest",
            "Elbows ~45 degrees"
          ],
          "commonMistakes": [
            "Bouncing the bar off the chest",
            "Flaring elbows to 90 degrees"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "38904614-5227-4e8d-bb14-2ab3f99e8822",
          "workoutPlanId": "91e7d7ae-d0ed-4144-aad8-8810d3e5fa0d",
          "exerciseId": "ca5be659-52a9-4cea-9d0c-93ec48da5a12",
          "orderIndex": 1,
          "setCount": 3,
          "targetReps": 8,
          "targetWeight": 50,
          "restSeconds": 90,
          "cue": "Press up and slightly back"
        },
        "exercise": {
          "id": "ca5be659-52a9-4cea-9d0c-93ec48da5a12",
          "name": "Incline Dumbbell Press",
          "primaryMuscleGroup": "Chest",
          "cues": [
            "Elbows 45 degrees",
            "Press up and slightly back"
          ],
          "commonMistakes": [
            "Setting the incline too steep",
            "Clanking the dumbbells at the top"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "2f917dcd-8f40-42a9-95fb-473db5f7b218",
          "workoutPlanId": "91e7d7ae-d0ed-4144-aad8-8810d3e5fa0d",
          "exerciseId": "2ad44028-d2cf-4235-af57-71bf65d58946",
          "orderIndex": 2,
          "setCount": 3,
          "targetReps": 8,
          "targetWeight": 40,
          "restSeconds": 90,
          "cue": "Core tight, full lockout"
        },
        "exercise": {
          "id": "2ad44028-d2cf-4235-af57-71bf65d58946",
          "name": "Seated Dumbbell Shoulder Press",
          "primaryMuscleGroup": "Shoulders",
          "cues": [
            "Core tight",
            "Press to lockout"
          ],
          "commonMistakes": [
            "Arching the back",
            "Half reps"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "80a6bb03-201e-4d06-b76b-baf374ae6d6c",
          "workoutPlanId": "91e7d7ae-d0ed-4144-aad8-8810d3e5fa0d",
          "exerciseId": "fbfe455c-0f80-4739-a582-9a1bae66bc51",
          "orderIndex": 3,
          "setCount": 3,
          "targetReps": 12,
          "targetWeight": 25,
          "restSeconds": 60,
          "cue": "Squeeze at the midline"
        },
        "exercise": {
          "id": "fbfe455c-0f80-4739-a582-9a1bae66bc51",
          "name": "Cable Chest Fly",
          "primaryMuscleGroup": "Chest",
          "cues": [
            "Slight elbow bend",
            "Squeeze at the midline"
          ],
          "commonMistakes": [
            "Turning it into a press",
            "Going too heavy"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "fde511f9-6500-48dd-9d17-eb7e447791bd",
          "workoutPlanId": "91e7d7ae-d0ed-4144-aad8-8810d3e5fa0d",
          "exerciseId": "c7ac997a-17c8-4ece-b9fb-bf59db481e78",
          "orderIndex": 4,
          "setCount": 3,
          "targetReps": 15,
          "targetWeight": 15,
          "restSeconds": 45,
          "cue": "Lead with the elbows"
        },
        "exercise": {
          "id": "c7ac997a-17c8-4ece-b9fb-bf59db481e78",
          "name": "Dumbbell Lateral Raise",
          "primaryMuscleGroup": "Shoulders",
          "cues": [
            "Lead with the elbows",
            "Stop at shoulder height"
          ],
          "commonMistakes": [
            "Swinging",
            "Shrugging the traps"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "3fff405f-dd05-48ac-807b-d514b74a7e71",
          "workoutPlanId": "91e7d7ae-d0ed-4144-aad8-8810d3e5fa0d",
          "exerciseId": "2d798b08-3d9c-4fbc-9e6e-b8e9836df226",
          "orderIndex": 5,
          "setCount": 3,
          "targetReps": 12,
          "targetWeight": 50,
          "restSeconds": 60,
          "cue": "Elbows fixed, full lockout"
        },
        "exercise": {
          "id": "2d798b08-3d9c-4fbc-9e6e-b8e9836df226",
          "name": "Cable Tricep Pushdown",
          "primaryMuscleGroup": "Arms",
          "cues": [
            "Elbows fixed",
            "Full lockout at the bottom"
          ],
          "commonMistakes": [
            "Letting elbows drift forward"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      }
    ]
  },
  {
    "plan": {
      "id": "368adf82-441b-4acd-8c44-c0dda82f04af",
      "ownerUserId": "ac5fb54d-08bb-4c08-be85-5fd0dc0e277a",
      "title": "Day 2 · Pull",
      "description": "Back and biceps",
      "estimatedDurationMinutes": 55,
      "createdAt": "2026-07-06T00:00:00.000Z",
      "updatedAt": "2026-07-06T00:00:00.000Z"
    },
    "steps": [
      {
        "step": {
          "id": "83a43768-5814-4194-841d-a1582fedd3e5",
          "workoutPlanId": "368adf82-441b-4acd-8c44-c0dda82f04af",
          "exerciseId": "7ebf60af-2b9a-4665-8988-860fad23e4aa",
          "orderIndex": 0,
          "setCount": 3,
          "targetReps": 5,
          "targetWeight": 185,
          "restSeconds": 180,
          "cue": "Flat back, drive the floor away"
        },
        "exercise": {
          "id": "7ebf60af-2b9a-4665-8988-860fad23e4aa",
          "name": "Conventional Deadlift",
          "primaryMuscleGroup": "Back",
          "cues": [
            "Bar over mid-foot",
            "Flat back",
            "Drive the floor away"
          ],
          "commonMistakes": [
            "Rounding the back",
            "Bar drifting forward"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "94a99d64-a5e6-45d1-a1a0-7e478122cd5c",
          "workoutPlanId": "368adf82-441b-4acd-8c44-c0dda82f04af",
          "exerciseId": "330fe080-c2ff-4e24-b389-e7726f4e7f93",
          "orderIndex": 1,
          "setCount": 3,
          "targetReps": 10,
          "targetWeight": 120,
          "restSeconds": 90,
          "cue": "Chest up, elbows down and back"
        },
        "exercise": {
          "id": "330fe080-c2ff-4e24-b389-e7726f4e7f93",
          "name": "Lat Pulldown",
          "primaryMuscleGroup": "Back",
          "cues": [
            "Chest up",
            "Pull elbows down and back"
          ],
          "commonMistakes": [
            "Leaning too far back",
            "Pulling behind the neck"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "8ffac45c-a009-4048-b7b3-3622a623d68e",
          "workoutPlanId": "368adf82-441b-4acd-8c44-c0dda82f04af",
          "exerciseId": "e03b6e30-79f3-42ec-b7ab-b4384b6bdbb3",
          "orderIndex": 2,
          "setCount": 3,
          "targetReps": 10,
          "targetWeight": 120,
          "restSeconds": 90,
          "cue": "Pull to the navel, squeeze"
        },
        "exercise": {
          "id": "e03b6e30-79f3-42ec-b7ab-b4384b6bdbb3",
          "name": "Seated Cable Row",
          "primaryMuscleGroup": "Back",
          "cues": [
            "Chest up",
            "Pull to the navel",
            "Squeeze the shoulder blades"
          ],
          "commonMistakes": [
            "Yanking with the lower back",
            "Rounding forward"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "ce26a101-0a19-449e-8938-fa2e884fb92f",
          "workoutPlanId": "368adf82-441b-4acd-8c44-c0dda82f04af",
          "exerciseId": "c2e261d9-526c-449a-8bc8-3ec0c353db7d",
          "orderIndex": 3,
          "setCount": 3,
          "targetReps": 8,
          "targetWeight": 95,
          "restSeconds": 90,
          "cue": "Flat back, pull to the ribs"
        },
        "exercise": {
          "id": "c2e261d9-526c-449a-8bc8-3ec0c353db7d",
          "name": "Bent-Over Barbell Row",
          "primaryMuscleGroup": "Back",
          "cues": [
            "Flat back",
            "Pull to the lower ribs",
            "Squeeze at the top"
          ],
          "commonMistakes": [
            "Standing too upright",
            "Using momentum"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "5c6aa478-0e8f-4b08-afe3-c3b1239310c5",
          "workoutPlanId": "368adf82-441b-4acd-8c44-c0dda82f04af",
          "exerciseId": "0898bc5f-d85a-49e8-bf17-a8d477ec6f64",
          "orderIndex": 4,
          "setCount": 3,
          "targetReps": 15,
          "targetWeight": 30,
          "restSeconds": 45,
          "cue": "Pull to the forehead, elbows high"
        },
        "exercise": {
          "id": "0898bc5f-d85a-49e8-bf17-a8d477ec6f64",
          "name": "Face Pull",
          "primaryMuscleGroup": "Shoulders",
          "cues": [
            "Pull to the forehead",
            "Elbows high"
          ],
          "commonMistakes": [
            "Going too heavy",
            "Using momentum"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "3424e078-6f18-4606-aec9-21ce0bbec0ee",
          "workoutPlanId": "368adf82-441b-4acd-8c44-c0dda82f04af",
          "exerciseId": "7be9f9c1-c6b4-4f91-95cf-093085d8b534",
          "orderIndex": 5,
          "setCount": 3,
          "targetReps": 10,
          "targetWeight": 25,
          "restSeconds": 60,
          "cue": "Elbows pinned, control down"
        },
        "exercise": {
          "id": "7be9f9c1-c6b4-4f91-95cf-093085d8b534",
          "name": "Dumbbell Bicep Curl",
          "primaryMuscleGroup": "Arms",
          "cues": [
            "Elbows pinned to the sides",
            "Control the lowering"
          ],
          "commonMistakes": [
            "Swinging the torso",
            "Half reps"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      }
    ]
  },
  {
    "plan": {
      "id": "58a2d16c-d56d-4d90-91a5-f111ac4d90ca",
      "ownerUserId": "ac5fb54d-08bb-4c08-be85-5fd0dc0e277a",
      "title": "Day 3 · Legs",
      "description": "Quads, hamstrings, glutes, calves",
      "estimatedDurationMinutes": 60,
      "createdAt": "2026-07-06T00:00:00.000Z",
      "updatedAt": "2026-07-06T00:00:00.000Z"
    },
    "steps": [
      {
        "step": {
          "id": "71a5f450-3065-45a2-9ba8-6c5280265379",
          "workoutPlanId": "58a2d16c-d56d-4d90-91a5-f111ac4d90ca",
          "exerciseId": "bc19bbd3-1b1f-4249-b7ea-11c9e00c8e2f",
          "orderIndex": 0,
          "setCount": 4,
          "targetReps": 6,
          "targetWeight": 185,
          "restSeconds": 180,
          "cue": "Brace, hit depth"
        },
        "exercise": {
          "id": "bc19bbd3-1b1f-4249-b7ea-11c9e00c8e2f",
          "name": "Barbell Back Squat",
          "primaryMuscleGroup": "Legs",
          "cues": [
            "Brace before descending",
            "Knees track over toes",
            "Hit depth"
          ],
          "commonMistakes": [
            "Heels lifting",
            "Collapsing knees inward"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "f0cdc76f-c9d0-46e7-8ff7-398437acd865",
          "workoutPlanId": "58a2d16c-d56d-4d90-91a5-f111ac4d90ca",
          "exerciseId": "ba23a70e-631a-4020-a1ad-871aa9444880",
          "orderIndex": 1,
          "setCount": 3,
          "targetReps": 8,
          "targetWeight": 135,
          "restSeconds": 120,
          "cue": "Push the hips back, bar close"
        },
        "exercise": {
          "id": "ba23a70e-631a-4020-a1ad-871aa9444880",
          "name": "Romanian Deadlift",
          "primaryMuscleGroup": "Legs",
          "cues": [
            "Soft knees",
            "Push hips back",
            "Bar close to the legs"
          ],
          "commonMistakes": [
            "Squatting instead of hinging",
            "Rounding the back"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "ec7b7429-caa1-4e50-9f11-be72161c6f82",
          "workoutPlanId": "58a2d16c-d56d-4d90-91a5-f111ac4d90ca",
          "exerciseId": "cddca2b4-5af3-4875-82af-1da1d77a450a",
          "orderIndex": 2,
          "setCount": 3,
          "targetReps": 12,
          "targetWeight": 270,
          "restSeconds": 90,
          "cue": "Full range, don't lock hard"
        },
        "exercise": {
          "id": "cddca2b4-5af3-4875-82af-1da1d77a450a",
          "name": "Leg Press",
          "primaryMuscleGroup": "Legs",
          "cues": [
            "Feet shoulder-width",
            "Full range",
            "Don't lock knees hard"
          ],
          "commonMistakes": [
            "Lower back rounding off the pad",
            "Bouncing at the bottom"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "c8e4837f-f183-4fd9-bb3b-63afbdf45c49",
          "workoutPlanId": "58a2d16c-d56d-4d90-91a5-f111ac4d90ca",
          "exerciseId": "d931505b-bb33-48e0-9e85-30d3ec518519",
          "orderIndex": 3,
          "setCount": 3,
          "targetReps": 12,
          "targetWeight": 70,
          "restSeconds": 60,
          "cue": "Curl fully, control the negative"
        },
        "exercise": {
          "id": "d931505b-bb33-48e0-9e85-30d3ec518519",
          "name": "Lying Leg Curl",
          "primaryMuscleGroup": "Legs",
          "cues": [
            "Curl fully",
            "Control the negative"
          ],
          "commonMistakes": [
            "Hips lifting off the pad",
            "Using momentum"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "6f53f655-67c9-4aed-8505-7fbfaecc39f0",
          "workoutPlanId": "58a2d16c-d56d-4d90-91a5-f111ac4d90ca",
          "exerciseId": "4ada7f13-d4d2-4212-b55f-cd5c0488b93e",
          "orderIndex": 4,
          "setCount": 3,
          "targetReps": 15,
          "targetWeight": 70,
          "restSeconds": 60,
          "cue": "Pause at the top"
        },
        "exercise": {
          "id": "4ada7f13-d4d2-4212-b55f-cd5c0488b93e",
          "name": "Leg Extension",
          "primaryMuscleGroup": "Legs",
          "cues": [
            "Pause at the top",
            "Control down"
          ],
          "commonMistakes": [
            "Swinging the weight",
            "Half reps"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "7cbcd66f-45a1-475b-ba63-78ba5b20df89",
          "workoutPlanId": "58a2d16c-d56d-4d90-91a5-f111ac4d90ca",
          "exerciseId": "d746fb4b-98b5-4f13-93a5-30792af46f57",
          "orderIndex": 5,
          "setCount": 4,
          "targetReps": 15,
          "targetWeight": 90,
          "restSeconds": 45,
          "cue": "Full stretch, pause at the top"
        },
        "exercise": {
          "id": "d746fb4b-98b5-4f13-93a5-30792af46f57",
          "name": "Standing Calf Raise",
          "primaryMuscleGroup": "Calves",
          "cues": [
            "Full stretch at the bottom",
            "Pause at the top"
          ],
          "commonMistakes": [
            "Bouncing",
            "Short range"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      }
    ]
  },
  {
    "plan": {
      "id": "d6e63884-95a1-4be7-a003-bbe43d150577",
      "ownerUserId": "ac5fb54d-08bb-4c08-be85-5fd0dc0e277a",
      "title": "Day 4 · Upper",
      "description": "Chest, back, shoulders, arms",
      "estimatedDurationMinutes": 55,
      "createdAt": "2026-07-06T00:00:00.000Z",
      "updatedAt": "2026-07-06T00:00:00.000Z"
    },
    "steps": [
      {
        "step": {
          "id": "312cac7c-a1be-45ef-a150-0a74a42e3c23",
          "workoutPlanId": "d6e63884-95a1-4be7-a003-bbe43d150577",
          "exerciseId": "14733cbd-3d5c-4c68-b10b-f6a51fa67596",
          "orderIndex": 0,
          "setCount": 4,
          "targetReps": 6,
          "targetWeight": 75,
          "restSeconds": 150,
          "cue": "Squeeze glutes, bar close to the face"
        },
        "exercise": {
          "id": "14733cbd-3d5c-4c68-b10b-f6a51fa67596",
          "name": "Overhead Press",
          "primaryMuscleGroup": "Shoulders",
          "cues": [
            "Squeeze glutes",
            "Bar path close to the face",
            "Lock out overhead"
          ],
          "commonMistakes": [
            "Arching the lower back",
            "Pressing around the chin"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "97a94e9a-840f-4903-994c-d7e424d35a9c",
          "workoutPlanId": "d6e63884-95a1-4be7-a003-bbe43d150577",
          "exerciseId": "a6db446f-4fd9-40cd-97e3-65fa7d31dbf5",
          "orderIndex": 1,
          "setCount": 3,
          "targetReps": 10,
          "targetWeight": 90,
          "restSeconds": 90,
          "cue": "Chest on the pad, row to the hips"
        },
        "exercise": {
          "id": "a6db446f-4fd9-40cd-97e3-65fa7d31dbf5",
          "name": "Chest-Supported Row",
          "primaryMuscleGroup": "Back",
          "cues": [
            "Chest on the pad",
            "Row to the hips"
          ],
          "commonMistakes": [
            "Lifting the chest off the pad",
            "Shrugging"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "7d636d6f-06f9-449e-aa80-74d3266407fe",
          "workoutPlanId": "d6e63884-95a1-4be7-a003-bbe43d150577",
          "exerciseId": "ca5be659-52a9-4cea-9d0c-93ec48da5a12",
          "orderIndex": 2,
          "setCount": 3,
          "targetReps": 8,
          "targetWeight": 50,
          "restSeconds": 90,
          "cue": "Elbows 45 degrees"
        },
        "exercise": {
          "id": "ca5be659-52a9-4cea-9d0c-93ec48da5a12",
          "name": "Incline Dumbbell Press",
          "primaryMuscleGroup": "Chest",
          "cues": [
            "Elbows 45 degrees",
            "Press up and slightly back"
          ],
          "commonMistakes": [
            "Setting the incline too steep",
            "Clanking the dumbbells at the top"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "2727dbfc-5c39-4af5-97eb-cf41fc2a4409",
          "workoutPlanId": "d6e63884-95a1-4be7-a003-bbe43d150577",
          "exerciseId": "330fe080-c2ff-4e24-b389-e7726f4e7f93",
          "orderIndex": 3,
          "setCount": 3,
          "targetReps": 10,
          "targetWeight": 120,
          "restSeconds": 90,
          "cue": "Chest up, pull elbows down"
        },
        "exercise": {
          "id": "330fe080-c2ff-4e24-b389-e7726f4e7f93",
          "name": "Lat Pulldown",
          "primaryMuscleGroup": "Back",
          "cues": [
            "Chest up",
            "Pull elbows down and back"
          ],
          "commonMistakes": [
            "Leaning too far back",
            "Pulling behind the neck"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "74d3e029-5ae1-4441-90e5-57bf13ebc56f",
          "workoutPlanId": "d6e63884-95a1-4be7-a003-bbe43d150577",
          "exerciseId": "c7ac997a-17c8-4ece-b9fb-bf59db481e78",
          "orderIndex": 4,
          "setCount": 3,
          "targetReps": 15,
          "targetWeight": 15,
          "restSeconds": 45,
          "cue": "Stop at shoulder height"
        },
        "exercise": {
          "id": "c7ac997a-17c8-4ece-b9fb-bf59db481e78",
          "name": "Dumbbell Lateral Raise",
          "primaryMuscleGroup": "Shoulders",
          "cues": [
            "Lead with the elbows",
            "Stop at shoulder height"
          ],
          "commonMistakes": [
            "Swinging",
            "Shrugging the traps"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "72a7af95-3431-449b-9bd4-3375ab504a75",
          "workoutPlanId": "d6e63884-95a1-4be7-a003-bbe43d150577",
          "exerciseId": "e1b82f1a-c09d-4495-870e-661aa76ecfd3",
          "orderIndex": 5,
          "setCount": 3,
          "targetReps": 12,
          "targetWeight": 25,
          "restSeconds": 60,
          "cue": "Neutral grip, elbows pinned"
        },
        "exercise": {
          "id": "e1b82f1a-c09d-4495-870e-661aa76ecfd3",
          "name": "Hammer Curl",
          "primaryMuscleGroup": "Arms",
          "cues": [
            "Neutral grip",
            "Elbows pinned"
          ],
          "commonMistakes": [
            "Swinging",
            "Half reps"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "a57e93ff-d93f-4ed0-ba7d-1bdd3894b77c",
          "workoutPlanId": "d6e63884-95a1-4be7-a003-bbe43d150577",
          "exerciseId": "2d798b08-3d9c-4fbc-9e6e-b8e9836df226",
          "orderIndex": 6,
          "setCount": 3,
          "targetReps": 12,
          "targetWeight": 50,
          "restSeconds": 60,
          "cue": "Full lockout at the bottom"
        },
        "exercise": {
          "id": "2d798b08-3d9c-4fbc-9e6e-b8e9836df226",
          "name": "Cable Tricep Pushdown",
          "primaryMuscleGroup": "Arms",
          "cues": [
            "Elbows fixed",
            "Full lockout at the bottom"
          ],
          "commonMistakes": [
            "Letting elbows drift forward"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      }
    ]
  },
  {
    "plan": {
      "id": "4cb363ff-8f35-4be5-ab55-c6aa52c624ac",
      "ownerUserId": "ac5fb54d-08bb-4c08-be85-5fd0dc0e277a",
      "title": "Day 5 · Lower",
      "description": "Legs and glutes",
      "estimatedDurationMinutes": 55,
      "createdAt": "2026-07-06T00:00:00.000Z",
      "updatedAt": "2026-07-06T00:00:00.000Z"
    },
    "steps": [
      {
        "step": {
          "id": "ac0affdb-9806-4178-954c-a13eb2ae0cc6",
          "workoutPlanId": "4cb363ff-8f35-4be5-ab55-c6aa52c624ac",
          "exerciseId": "d5765b06-2c62-4d06-9816-a23715ff9ee3",
          "orderIndex": 0,
          "setCount": 3,
          "targetReps": 8,
          "targetWeight": 135,
          "restSeconds": 150,
          "cue": "Elbows high, upright torso"
        },
        "exercise": {
          "id": "d5765b06-2c62-4d06-9816-a23715ff9ee3",
          "name": "Front Squat",
          "primaryMuscleGroup": "Legs",
          "cues": [
            "Elbows high",
            "Upright torso",
            "Brace hard"
          ],
          "commonMistakes": [
            "Elbows dropping",
            "Heels lifting"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "b375c256-8a45-4df2-984e-19ec75eb3621",
          "workoutPlanId": "4cb363ff-8f35-4be5-ab55-c6aa52c624ac",
          "exerciseId": "24027759-4bbc-41f6-91a3-34dfd5231151",
          "orderIndex": 1,
          "setCount": 3,
          "targetReps": 10,
          "targetWeight": 185,
          "restSeconds": 90,
          "cue": "Drive through heels, squeeze at top"
        },
        "exercise": {
          "id": "24027759-4bbc-41f6-91a3-34dfd5231151",
          "name": "Hip Thrust",
          "primaryMuscleGroup": "Glutes",
          "cues": [
            "Chin tucked",
            "Drive through the heels",
            "Squeeze at the top"
          ],
          "commonMistakes": [
            "Overarching the back",
            "Short range"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "5ad0e051-29c4-478d-8125-d52a5bf158be",
          "workoutPlanId": "4cb363ff-8f35-4be5-ab55-c6aa52c624ac",
          "exerciseId": "1499c34f-71a5-4615-a10c-d89f64aef30b",
          "orderIndex": 2,
          "setCount": 3,
          "targetReps": 12,
          "targetWeight": 30,
          "restSeconds": 75,
          "cue": "Long stride, knee over ankle"
        },
        "exercise": {
          "id": "1499c34f-71a5-4615-a10c-d89f64aef30b",
          "name": "Walking Lunge",
          "primaryMuscleGroup": "Legs",
          "cues": [
            "Long stride",
            "Knee over ankle",
            "Tall torso"
          ],
          "commonMistakes": [
            "Steps too short",
            "Front knee caving in"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "3befe26f-caeb-430d-86d3-d70734c97ce7",
          "workoutPlanId": "4cb363ff-8f35-4be5-ab55-c6aa52c624ac",
          "exerciseId": "d931505b-bb33-48e0-9e85-30d3ec518519",
          "orderIndex": 3,
          "setCount": 3,
          "targetReps": 12,
          "targetWeight": 70,
          "restSeconds": 60,
          "cue": "Curl fully"
        },
        "exercise": {
          "id": "d931505b-bb33-48e0-9e85-30d3ec518519",
          "name": "Lying Leg Curl",
          "primaryMuscleGroup": "Legs",
          "cues": [
            "Curl fully",
            "Control the negative"
          ],
          "commonMistakes": [
            "Hips lifting off the pad",
            "Using momentum"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "b9f7e907-99be-4f5f-abf8-4fccab97db50",
          "workoutPlanId": "4cb363ff-8f35-4be5-ab55-c6aa52c624ac",
          "exerciseId": "4ada7f13-d4d2-4212-b55f-cd5c0488b93e",
          "orderIndex": 4,
          "setCount": 3,
          "targetReps": 15,
          "targetWeight": 70,
          "restSeconds": 60,
          "cue": "Pause at the top"
        },
        "exercise": {
          "id": "4ada7f13-d4d2-4212-b55f-cd5c0488b93e",
          "name": "Leg Extension",
          "primaryMuscleGroup": "Legs",
          "cues": [
            "Pause at the top",
            "Control down"
          ],
          "commonMistakes": [
            "Swinging the weight",
            "Half reps"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      },
      {
        "step": {
          "id": "89dc0213-38d8-4962-bc69-88db225fdb04",
          "workoutPlanId": "4cb363ff-8f35-4be5-ab55-c6aa52c624ac",
          "exerciseId": "a1b345f6-5304-41b7-bdee-bbcefa1d1628",
          "orderIndex": 5,
          "setCount": 4,
          "targetReps": 15,
          "targetWeight": 45,
          "restSeconds": 45,
          "cue": "Full stretch, pause at the top"
        },
        "exercise": {
          "id": "a1b345f6-5304-41b7-bdee-bbcefa1d1628",
          "name": "Seated Calf Raise",
          "primaryMuscleGroup": "Calves",
          "cues": [
            "Full stretch",
            "Pause at the top"
          ],
          "commonMistakes": [
            "Bouncing",
            "Partial range"
          ],
          "createdAt": "2026-07-06T00:00:00.000Z",
          "updatedAt": "2026-07-06T00:00:00.000Z"
        }
      }
    ]
  }
];
